# -*- coding: utf-8 -*-
"""Colab-Ai-Draw

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104yO2a6p8_Fd7Cr_G70O_oq-5zYRtVss
"""

import os, sys, gc, warnings, shutil, subprocess, importlib, platform, time, random
from pathlib import Path
from datetime import datetime

# ============================================================
# 1. 环境清理 & 缓存重定向
# ============================================================
warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['CUDA_LAUNCH_BLOCKING'] = '3'
for v in ['DIFFUSERS_VERBOSITY', 'HUGGINGFACE_HUB_VERBOSITY', 'TRANSFORMERS_VERBOSITY']:
    os.environ[v] = 'error'

# 强制设置缓存到 /tmp，并每次启动时删除
os.environ['HF_HUB_CACHE'] = '/tmp/hf_cache'
for _d in ['/tmp/hf_cache', '/tmp/torch_cache', '/tmp/__pycache__']:
    if os.path.exists(_d):
        shutil.rmtree(_d, ignore_errors=True)
gc.collect()

import torch
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.synchronize()
    free, total = torch.cuda.mem_get_info()
    print(f'GPU memory: {free/1024**3:.1f}/{total/1024**3:.1f} GB')
else:
    print('WARNING: CUDA not available.')

print(f'Python {sys.version.split()[0]} | {platform.system()} {platform.release()}')
if torch.cuda.is_available():
    p = torch.cuda.get_device_properties(0)
    print(f'{p.name} | VRAM: {p.total_memory/1024**3:.1f}GB | CUDA {torch.version.cuda}')

# ============================================================
# 2. 依赖安装
# ============================================================
_REQUIRED = ['diffusers', 'transformers', 'accelerate', 'safetensors', 'matplotlib', 'gradio']
_missing = [p for p in _REQUIRED if not importlib.util.find_spec(p.replace('-', '_'))]
if _missing:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade'] + _missing)
subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', 'pillow>=8.0,<12.0'])

from diffusers import StableDiffusionXLPipeline
from huggingface_hub import login
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
import gradio as gr

# ============================================================
# 3. Hugging Face 登录（可选）
# ============================================================
HF_TOKEN = os.environ.get('HF_TOKEN', '') or ''
if HF_TOKEN and len(HF_TOKEN) > 10:
    try:
        login(token=HF_TOKEN, add_to_git_credential=False)
        print('HF login OK')
    except Exception as e:
        print(f'HF token invalid: {e}')

# ============================================================
# 4. 加载模型（移除 variant 参数）
# ============================================================
MODEL_ID = 'cagliostrolab/animagine-xl-4.0'
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
DTYPE = torch.float16 if DEVICE == 'cuda' else torch.float32

print(f'Loading {MODEL_ID} on {DEVICE}...')
try:
    pipe = StableDiffusionXLPipeline.from_pretrained(
        MODEL_ID,
        torch_dtype=DTYPE,
        use_safetensors=True,
        # 移除 variant，因模型仓库无该变体
    )
except Exception as e:
    print(f'Failed to load model: {e}')
    print('Please check your internet connection or model availability.')
    raise

if DEVICE == 'cuda':
    pipe.enable_attention_slicing()
    pipe.enable_vae_slicing()
    pipe.enable_model_cpu_offload()
    torch.cuda.empty_cache()
print(f'UNet params: {sum(p.numel() for p in pipe.unet.parameters())/1e6:.1f}M')

# ============================================================
# 5. 生成函数（不保存图片，直接返回 PIL 列表）
# ============================================================
def generate(prompt, negative_prompt='', width=1024, height=1024, steps=25,
             guidance=7.0, seed=-1, num_images=1):
    prompt = (prompt or '').strip()
    negative_prompt = (negative_prompt or '').strip()
    if not prompt:
        return [], 'Please enter a prompt.'
    seed = random.randint(0, 2**32 - 1) if seed == -1 else seed
    generator = torch.Generator(device='cpu').manual_seed(seed)
    start = time.time()
    try:
        with torch.no_grad():
            result = pipe(prompt=prompt,
                          negative_prompt=negative_prompt if negative_prompt else None,
                          width=width, height=height,
                          num_inference_steps=steps,
                          guidance_scale=guidance,
                          generator=generator,
                          num_images_per_prompt=num_images)
    except Exception as e:
        return [], f'Generation failed: {str(e)}'
    elapsed = time.time() - start
    # 不再保存到磁盘，直接返回图片列表
    return result.images, f'Done in {elapsed:.1f}s (seed={seed})'

# ============================================================
# 6. Gradio UI（简化，移除历史记录）
# ============================================================
def build_ui():
    with gr.Blocks(title='AI Drawing Platform SDXL', theme=gr.themes.Soft(),
                   css='footer{display:none !important}') as ui:
        gr.Markdown('# AI Drawing Platform SDXL')
        gr.Markdown(f'**{MODEL_ID}** | {DEVICE.upper()} | 缓存：`/tmp/hf_cache`（每次启动自动清空）')
        with gr.Row():
            with gr.Column(scale=2):
                p = gr.Textbox(label='Prompt', placeholder='masterpiece, best quality, 1girl, ...', lines=3)
                n = gr.Textbox(label='Negative Prompt', placeholder='nsfw, lowres, bad anatomy, ...', lines=2)
                with gr.Row():
                    w = gr.Dropdown(label='Width', choices=[512, 640, 768, 896, 1024], value=1024)
                    h = gr.Dropdown(label='Height', choices=[512, 640, 768, 896, 1024], value=1024)
                with gr.Row():
                    s = gr.Slider(label='Steps', minimum=10, maximum=50, value=25, step=1)
                    g = gr.Slider(label='Guidance', minimum=1.0, maximum=15.0, value=7.0, step=0.5)
                with gr.Row():
                    sd = gr.Number(label='Seed (-1=random)', value=-1, precision=0)
                    ni = gr.Dropdown(label='N', choices=[1, 2, 3, 4], value=1)
                btn = gr.Button('Generate', variant='primary', size='lg')
                msg = gr.Textbox(label='Status', interactive=False)
            with gr.Column(scale=3):
                gal = gr.Gallery(label='Generated Images', columns=2, object_fit='contain', height='auto')
        btn.click(fn=generate, inputs=[p, n, w, h, s, g, sd, ni], outputs=[gal, msg])
    return ui

def launch_web():
    import socket
    port = 7860
    for _ in range(10):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            if s.connect_ex(('127.0.0.1', port)) != 0:
                break
        port += 1
    ui = build_ui()
    print(f'\nStarting web server on port {port}...')
    ui.launch(server_name='0.0.0.0', server_port=port, share=True, debug=False)
    while True:
        time.sleep(1)

if __name__ == '__main__':
    launch_web()